; BELOW CODE ADDS AB20H + 65DE = 110FE WITH CARRY FLAG SET 

ORG 5000H
CLR C     ;MAKE CY=0
MOV A,#020H  ;LOWER BYTE OF OPERAND 1 IN A
ADD A,#0DEH  ;ADD LOWER BYTE OF OPERAND 2 WITH A
MOV R1,A  ;STORES LSB OF RESULT IN R1
MOV A,#65H  ;HIGHER BYTE OF OPERAND 2 IN A
ADDC A,#0ABH ; ADD WITH HIGHER BYTE OF OPERAND 1
MOV R0,A  ;STORES MSB OF RESULT IN R0
END
