; 8051 ASSEMBLY CODE 
; ALP TO SUBTRACT TWO 16 BIT NUMBER
; BELOW CODE SUBTRACTS AB20H - 65DE = B942H 

	ORG 3000H
	CLR C	  		; MAKE CY=0
	MOV A, #020H		; LOWER BYTE OF OPERAND 1 IN A
	SUBB A, #0DEH	              ; SUBTRACT LOWER BYTE OF OPERAND 2 WITH A
	MOV R1, A		; STORES LSB OF RESULT IN R1
	MOV A, #65H		; HIGHER BYTE OF OPERAND 2 IN A
	SUBB A, #0ABH	               ; SUBTRACT WITH HIGHER BYTE OF OPERAND 1
	MOV R0, A		; STORES MSB OF RESULT IN R0
	END
